//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taekwondoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int student_id { get; set; }
        public int class_id { get; set; }
        public System.DateTime class_date { get; set; }
        public bool did_attend { get; set; }
    
        public virtual student_class student_class { get; set; }
        public virtual student student { get; set; }
    }
}
