//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taekwondoApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taekwondoDBEntities : DbContext
    {
        public taekwondoDBEntities()
            : base("name=taekwondoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<money_tracking> money_tracking { get; set; }
        public virtual DbSet<parent> parents { get; set; }
        public virtual DbSet<rank> ranks { get; set; }
        public virtual DbSet<register_student> register_student { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<student_class> student_class { get; set; }
    }
}
